<?php
//FUNCION ABLIGATORIA PARA INICIO DE SESION
session_start();
$login = 'Carlos';

//UNA VEZ INICIADA LA SESION LA PODEMOS ASOCIAR A UNA CONSTANTE PARA DEFINIRLE EL ROL
//VIAJA A CUALQUIER PARTE DEL SITIO QUE TENGA LA FUNCION SESSION START
$_SESSION['admin'] = $login;

//COMPROBAMOS CON ISSET SI EXITE ESTA VARIABLE O CONSTANTE
if( isset($_SESSION['admin']) ){
  HEADER('location:index.php');
  //echo 'Sesion Inicidada';
}

 ?>
